### ISSUE TITLE
[CHECKLIST] READMEs for all Blueprints

### ISSUE THREAD

**Issue by Tjemmmic** [tangle-network/gadget#273]
# Overview

As we build out Blueprints to show off their uses, we want to make sure that we have clear READMEs for all of them.

## Checklist

- [x] Tangle Incredible Squaring Blueprint
- [ ] Eigen Incredible Squaring AVS Blueprint
- [ ] MPC Blueprint
- [ ] Tangle AVS Blueprint
- [ ] BLS Aggregator Blueprint
