### ISSUE TITLE
[CHECKLIST] CLI improvements

### ISSUE THREAD

**Issue by Serial-ATA** [tangle-network/gadget#354]
# Overview

In order:

- [ ] https://github.com/tangle-network/gadget/issues/353
- [ ] https://github.com/tangle-network/gadget/issues/352
- [ ] https://github.com/tangle-network/tangle-docs/issues/73
