### ISSUE TITLE
[CHECKLIST] Migrate gadget-workspace back into SDK

### ISSUE THREAD

**Issue by drewstone** [tangle-network/gadget#549]
# Overview
Gadget workspace is being used to rewrite the gadget SDK as separate crates.
- https://github.com/tangle-network/gadget-workspace

## Checklist
- [x] tangle-network/gadget#550
- [x] tangle-network/gadget#551
- [x] tangle-network/gadget#552
- [x] tangle-network/gadget#553
- [x] tangle-network/gadget#554
- [x] tangle-network/gadget#555
- [x] tangle-network/gadget#556
- [x] tangle-network/gadget#557
- [x] tangle-network/gadget#558
- [x] tangle-network/gadget-workspace#27
- [x] tangle-network/gadget#560
- [x] tangle-network/gadget#561
- [x] tangle-network/gadget-workspace#26
- [x] tangle-network/gadget-workspace#23
- [x] tangle-network/gadget-workspace#25
- [x] #586
- [x] #587
- [x] #588
- [x] [TASK] Migrate macros over, feature gate tangle vs. evm
- [x] [TASK] Migrate the blueprint manager and improve
- [ ] [TASK] Remove bytes from runtime and workspace migration https://github.com/tangle-network/tangle/issues/834
- [x] [TASK] Migrate blueprint build utils
- [x] [TASK] Migrate blueprint metadata (dependent on macros)
- [x] [TASK] Create a library for converting docker compose yaml files to bollard `Container`s.
- [x] #589

## Don't migrate
- Slashing
- Tracer
- GadgetRunner

## Questions / considerations
1. What if anything can be considered plugin/extension that doesn't belong in the SDK?
2. Future support for iroh, consensus protocols, kubernetes, TEE support
